In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import math
import numpy as np
data = pd.read_csv("DSS4.csv")
data

X1   X2     X3     X4    X5
0   6.8  225  0.442  0.672   9.2
1   6.3  180  0.435  0.797  11.7
2   6.4  190  0.456  0.761  15.8
3   6.2  180  0.416  0.651   8.6
4   6.9  205  0.449  0.900  23.2
5   6.4  225  0.431  0.780  27.4
6   6.3  185  0.487  0.771   9.3
7   6.8  235  0.469  0.750  16.0
8   6.9  235  0.435  0.818   4.7
9   6.7  210  0.480  0.825  12.5
10  6.9  245  0.516  0.632  20.1
11  6.9  245  0.493  0.757   9.1
12  6.3  185  0.374  0.709   8.1
13  6.1  185  0.424  0.782   8.6
14  6.2  180  0.441  0.775  20.3
15  6.8  220  0.503  0.880  25.0
16  6.5  194  0.503  0.833  19.2
17  7.6  225  0.425  0.571   3.3
18  6.3  210  0.371  0.816  11.2
19  7.1  240  0.504  0.714  10.5
20  6.8  225  0.400  0.765  10.1
21  7.3  263  0.482  0.655   7.2
22  6.4  210  0.475  0.244  13.6
23  6.8  235  0.428  0.728   9.0
24  7.2  230  0.559  0.721  24.6
25  6.4  190  0.441  0.757  12.6
26  6.6  220  0.492  0.747   5.6
27  6.8  210  0.402  0.739   8.7
28  6.1  180  0.415  0.713   7.7
29  6.5  235  0.492  0.742  24.1
30  6.4  185  0.484  0.861  11.7
31  6.0  175  0.387  0.721   7.7
32  6.0  192  0.436  0.785   9.6
33  7.3  263  0.482  0.655   7.2
34  6.1  180  0.340  0.821  12.3
35  6.7  240  0.516  0.728   8.9
36  6.4  210  0.475  0.846  13.6
37  5.8  160  0.412  0.813  11.2
38  6.9  230  0.411  0.595   2.8
39  7.0  245  0.407  0.573   3.2
40  7.3  228  0.445  0.726   9.4
41  5.9  155  0.291  0.707  11.9
42  6.2  200  0.449  0.804  15.4
43  6.8  235  0.546  0.784   7.4
44  7.0  235  0.480  0.744  18.9
45  5.9  105  0.359  0.839   7.9
46  6.1  180  0.528  0.790  12.2
47  5.7  185  0.352  0.701  11.0
48  7.1  245  0.414  0.778   2.8
49  5.8  180  0.425  0.872  11.8
50  7.4  240  0.599  0.713  17.1
51  6.8  225  0.482  0.701  11.6
52  6.8  215  0.457  0.734   5.8
53  7.0  230  0.435  0.764   8.3

In [19]:
df=data
y=data.X5
d=df.drop(["X5"],axis=1)
d.insert(0,"Bias",1)
d

Bias   X1   X2     X3     X4
0      1  6.8  225  0.442  0.672
1      1  6.3  180  0.435  0.797
2      1  6.4  190  0.456  0.761
3      1  6.2  180  0.416  0.651
4      1  6.9  205  0.449  0.900
5      1  6.4  225  0.431  0.780
6      1  6.3  185  0.487  0.771
7      1  6.8  235  0.469  0.750
8      1  6.9  235  0.435  0.818
9      1  6.7  210  0.480  0.825
10     1  6.9  245  0.516  0.632
11     1  6.9  245  0.493  0.757
12     1  6.3  185  0.374  0.709
13     1  6.1  185  0.424  0.782
14     1  6.2  180  0.441  0.775
15     1  6.8  220  0.503  0.880
16     1  6.5  194  0.503  0.833
17     1  7.6  225  0.425  0.571
18     1  6.3  210  0.371  0.816
19     1  7.1  240  0.504  0.714
20     1  6.8  225  0.400  0.765
21     1  7.3  263  0.482  0.655
22     1  6.4  210  0.475  0.244
23     1  6.8  235  0.428  0.728
24     1  7.2  230  0.559  0.721
25     1  6.4  190  0.441  0.757
26     1  6.6  220  0.492  0.747
27     1  6.8  210  0.402  0.739
28     1  6.1  180  0.415  0.713
29     1  6.5  235  0.492  0.742
30     1  6.4  185  0.484  0.861
31     1  6.0  175  0.387  0.721
32     1  6.0  192  0.436  0.785
33     1  7.3  263  0.482  0.655
34     1  6.1  180  0.340  0.821
35     1  6.7  240  0.516  0.728
36     1  6.4  210  0.475  0.846
37     1  5.8  160  0.412  0.813
38     1  6.9  230  0.411  0.595
39     1  7.0  245  0.407  0.573
40     1  7.3  228  0.445  0.726
41     1  5.9  155  0.291  0.707
42     1  6.2  200  0.449  0.804
43     1  6.8  235  0.546  0.784
44     1  7.0  235  0.480  0.744
45     1  5.9  105  0.359  0.839
46     1  6.1  180  0.528  0.790
47     1  5.7  185  0.352  0.701
48     1  7.1  245  0.414  0.778
49     1  5.8  180  0.425  0.872
50     1  7.4  240  0.599  0.713
51     1  6.8  225  0.482  0.701
52     1  6.8  215  0.457  0.734
53     1  7.0  230  0.435  0.764

In [20]:
res1=np.linalg.inv(np.matmul(d.T.to_numpy(),d.to_numpy()))
res1

array([[ 7.53757318e+00, -1.17033908e+00,  9.05578971e-03,
        -5.10231521e-01, -1.99731860e+00],
       [-1.17033908e+00,  3.01458004e-01, -3.54820732e-03,
        -2.30808550e-01,  4.45880442e-02],
       [ 9.05578971e-03, -3.54820732e-03,  7.32142753e-05,
        -5.88180251e-03,  2.14294470e-03],
       [-5.10231521e-01, -2.30808550e-01, -5.88180251e-03,
         8.42927479e+00, -7.01583563e-01],
       [-1.99731860e+00,  4.45880442e-02,  2.14294470e-03,
        -7.01583563e-01,  2.11482185e+00]])

In [21]:
res2=np.matmul(d.T.to_numpy(),y.to_numpy())
res2

array([   636.7   ,   4184.08  , 133554.9   ,    291.9388,    480.0038])

In [23]:
res3=np.matmul(res1,res2)
res3

array([ 4.14870671e+00, -3.69049908e+00,  9.45845788e-03,  4.79401992e+01,
        1.13710193e+01])

In [24]:
y_pred=res3[0]+res3[1]*d.X1+res3[2]*d.X2+res3[3]*d.X3+res3[4]*d.X4
y_pred

0     10.012359
1     12.517774
2     12.840696
3     10.315791
4     12.382314
5     12.189286
6     14.762310
7     12.288268
8     11.062481
9     13.801025
10    12.925212
11    13.243965
12     8.640064
13    12.605259
14    12.924303
15    15.254591
16    15.581383
17     5.096503
18     9.949404
19    12.496961
20     9.056375
21    10.250831
22     8.061912
23    10.072558
24    14.749635
25    12.076109
26    13.953003
27     8.714732
28    11.341904
29    14.407075
30    15.272831
31    10.412304
32    13.649913
33    10.250831
34     8.974459
35    14.707638
36    14.907266
37    13.253166
38     7.328887
39     6.659790
40     8.953340
41     5.830732
42    13.826753
43    16.366278
44    12.009285
45    10.118717
46    17.634715
47     9.708711
48     8.957381
49    14.736448
50    15.932759
51    12.259726
52    11.341881
53    10.032104
dtype: float64

In [25]:
y_bar=sum(y)/len(y)
y_bar

11.79074074074074

In [27]:
s1=(y_pred-y_bar)*(y_pred-y_bar)

In [29]:
s2=(y-y_bar)*(y-y_bar)

In [30]:
r2=sum(s1)/sum(s2)
r2


0.22225063130016773

In [34]:
MS=(y-y_pred)**2
MSE=sum(MS)/(len(y))
RMSE=math.sqrt(MSE)

In [35]:
MSE

26.56540328507955

In [36]:
RMSE

5.154163684350697