In [56]:
import pandas as pd
import numpy as np
cols=['B','X1','X2','X3','X4','Y']

mr=pd.read_csv('Ds4.csv')
mr['B']=1
mr


X1   X2     X3     X4     Y  B
0   6.8  225  0.442  0.672   9.2  1
1   6.3  180  0.435  0.797  11.7  1
2   6.4  190  0.456  0.761  15.8  1
3   6.2  180  0.416  0.651   8.6  1
4   6.9  205  0.449  0.900  23.2  1
5   6.4  225  0.431  0.780  27.4  1
6   6.3  185  0.487  0.771   9.3  1
7   6.8  235  0.469  0.750  16.0  1
8   6.9  235  0.435  0.818   4.7  1
9   6.7  210  0.480  0.825  12.5  1
10  6.9  245  0.516  0.632  20.1  1
11  6.9  245  0.493  0.757   9.1  1
12  6.3  185  0.374  0.709   8.1  1
13  6.1  185  0.424  0.782   8.6  1
14  6.2  180  0.441  0.775  20.3  1
15  6.8  220  0.503  0.880  25.0  1
16  6.5  194  0.503  0.833  19.2  1
17  7.6  225  0.425  0.571   3.3  1
18  6.3  210  0.371  0.816  11.2  1
19  7.1  240  0.504  0.714  10.5  1
20  6.8  225  0.400  0.765  10.1  1
21  7.3  263  0.482  0.655   7.2  1
22  6.4  210  0.475  0.244  13.6  1
23  6.8  235  0.428  0.728   9.0  1
24  7.2  230  0.559  0.721  24.6  1
25  6.4  190  0.441  0.757  12.6  1
26  6.6  220  0.492  0.747   5.6  1
27  6.8  210  0.402  0.739   8.7  1
28  6.1  180  0.415  0.713   7.7  1
29  6.5  235  0.492  0.742  24.1  1
30  6.4  185  0.484  0.861  11.7  1
31  6.0  175  0.387  0.721   7.7  1
32  6.0  192  0.436  0.785   9.6  1
33  7.3  263  0.482  0.655   7.2  1
34  6.1  180  0.340  0.821  12.3  1
35  6.7  240  0.516  0.728   8.9  1
36  6.4  210  0.475  0.846  13.6  1
37  5.8  160  0.412  0.813  11.2  1
38  6.9  230  0.411  0.595   2.8  1
39  7.0  245  0.407  0.573   3.2  1
40  7.3  228  0.445  0.726   9.4  1
41  5.9  155  0.291  0.707  11.9  1
42  6.2  200  0.449  0.804  15.4  1
43  6.8  235  0.546  0.784   7.4  1
44  7.0  235  0.480  0.744  18.9  1
45  5.9  105  0.359  0.839   7.9  1
46  6.1  180  0.528  0.790  12.2  1
47  5.7  185  0.352  0.701  11.0  1
48  7.1  245  0.414  0.778   2.8  1
49  5.8  180  0.425  0.872  11.8  1
50  7.4  240  0.599  0.713  17.1  1
51  6.8  225  0.482  0.701  11.6  1
52  6.8  215  0.457  0.734   5.8  1
53  7.0  230  0.435  0.764   8.3  1

In [70]:


x=pd.DataFrame({"Bias":mr['B'],"X1":mr['X1'],"X2":mr['X2'],"X3":mr['X3'],"X4":mr['X4']})
print(x)
y=pd.DataFrame({"Y":mr['Y']})
print(y)

x=x.to_numpy()
y=y.to_numpy()

xt = x.transpose()
xt

               

    Bias   X1   X2     X3     X4
0      1  6.8  225  0.442  0.672
1      1  6.3  180  0.435  0.797
2      1  6.4  190  0.456  0.761
3      1  6.2  180  0.416  0.651
4      1  6.9  205  0.449  0.900
5      1  6.4  225  0.431  0.780
6      1  6.3  185  0.487  0.771
7      1  6.8  235  0.469  0.750
8      1  6.9  235  0.435  0.818
9      1  6.7  210  0.480  0.825
10     1  6.9  245  0.516  0.632
11     1  6.9  245  0.493  0.757
12     1  6.3  185  0.374  0.709
13     1  6.1  185  0.424  0.782
14     1  6.2  180  0.441  0.775
15     1  6.8  220  0.503  0.880
16     1  6.5  194  0.503  0.833
17     1  7.6  225  0.425  0.571
18     1  6.3  210  0.371  0.816
19     1  7.1  240  0.504  0.714
20     1  6.8  225  0.400  0.765
21     1  7.3  263  0.482  0.655
22     1  6.4  210  0.475  0.244
23     1  6.8  235  0.428  0.728
24     1  7.2  230  0.559  0.721
25     1  6.4  190  0.441  0.757
26     1  6.6  220  0.492  0.747
27     1  6.8  210  0.402  0.739
28     1  6.1  180  0.415  0.713
29     1  

array([[1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00],
       [6.80e+00, 6.30e+00, 6.40e+00, 6.20e+00, 6.90e+00, 6.40e+00,
        6.30e+00, 6.80e+00, 6.90e+00, 6.70e+00, 6.90e+00, 6.90e+00,
        6.30e+00, 6.10e+00, 6.20e+00, 6.80e+00, 6.50e+00, 7.60e+00,
        6.30e+00, 7.10e+00, 6.80e+00, 7.30e+00, 6.40e+00, 6.80e+00,
        7.20e+00, 6.40e+00, 6.60e+00, 6.80e+00, 6.10e+00, 6.50e+00,
        6.40e+00, 6.00e+00, 6.00e+00, 7.30e+00,

In [73]:
xtx = np.matmul(xt,x)
xtx

array([[5.4000000e+01, 3.5570000e+02, 1.1335000e+04, 2.4252000e+01,
        4.0060000e+01],
       [3.5570000e+02, 2.3541700e+03, 7.5278200e+04, 1.6043040e+02,
        2.6324520e+02],
       [1.1335000e+04, 7.5278200e+04, 2.4278470e+06, 5.1374860e+03,
        8.3622800e+03],
       [2.4252000e+01, 1.6043040e+02, 5.1374860e+03, 1.1061340e+01,
        1.7985817e+01],
       [4.0060000e+01, 2.6324520e+02, 8.3622800e+03, 1.7985817e+01,
        3.0250134e+01]])

In [75]:
in_xtx = np.linalg.inv(xtx)
print(in_xtx)

[[ 7.53757318e+00 -1.17033908e+00  9.05578971e-03 -5.10231521e-01
  -1.99731860e+00]
 [-1.17033908e+00  3.01458004e-01 -3.54820732e-03 -2.30808550e-01
   4.45880442e-02]
 [ 9.05578971e-03 -3.54820732e-03  7.32142753e-05 -5.88180251e-03
   2.14294470e-03]
 [-5.10231521e-01 -2.30808550e-01 -5.88180251e-03  8.42927479e+00
  -7.01583563e-01]
 [-1.99731860e+00  4.45880442e-02  2.14294470e-03 -7.01583563e-01
   2.11482185e+00]]


In [77]:
in_xtx_xt = np.matmul(in_xtx,xt)
in_xtx_xt

array([[ 4.90997016e-02, -1.93345009e-02,  1.53780961e-02,
         3.99002321e-01, -7.08010262e-01,  3.07137471e-01,
         5.13426922e-02, -2.99095032e-02, -2.65413204e-01,
        -2.94681780e-01,  1.55317199e-01, -8.26123006e-02,
         2.32832607e-01,  2.95584589e-01,  1.38579027e-01,
        -4.42745639e-01, -2.33220474e-01, -6.76768446e-01,
         2.47044954e-01, -2.81686912e-01, -1.15221204e-01,
        -1.78404673e-01,  1.21941321e+00,  3.49509983e-02,
        -5.31322680e-01,  3.10208433e-02,  6.25780975e-02,
        -2.00148229e-01,  3.92712707e-01,  3.25435444e-01,
        -2.43919195e-01,  4.62775600e-01,  4.63894291e-01,
        -1.78404673e-01,  2.15269663e-01,  1.52363481e-01,
         1.70274104e-02,  3.64497471e-01,  1.46955452e-01,
         2.11740325e-01, -6.18288367e-01,  4.75638400e-01,
         2.57690730e-01, -1.37106163e-01, -2.57605954e-01,
        -2.75492884e-01,  1.81263013e-01,  9.62239696e-01,
        -3.18315517e-01,  4.21138458e-01, -6.79263311e-0